// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"time"

	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/gid"
	"go.probo.inc/probo/pkg/mail"
	"go.probo.inc/probo/pkg/page"
)

type Node interface {
	IsNode()
	GetID() gid.GID
}

type AcceptNonDisclosureAgreementInput struct {
	FullName string `json:"fullName"`
}

type AcceptNonDisclosureAgreementPayload struct {
	Success bool `json:"success"`
}

type Audit struct {
	ID        gid.GID    `json:"id"`
	Framework *Framework `json:"framework"`
	Report    *Report    `json:"report,omitempty"`
}

func (Audit) IsNode()             {}
func (this Audit) GetID() gid.GID { return this.ID }

type AuditConnection struct {
	Edges    []*AuditEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type AuditEdge struct {
	Cursor page.CursorKey `json:"cursor"`
	Node   *Audit         `json:"node"`
}

type Document struct {
	ID                     gid.GID               `json:"id"`
	Title                  string                `json:"title"`
	DocumentType           coredata.DocumentType `json:"documentType"`
	IsUserAuthorized       bool                  `json:"isUserAuthorized"`
	HasUserRequestedAccess bool                  `json:"hasUserRequestedAccess"`
}

func (Document) IsNode()             {}
func (this Document) GetID() gid.GID { return this.ID }

type DocumentConnection struct {
	Edges    []*DocumentEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type DocumentEdge struct {
	Cursor page.CursorKey `json:"cursor"`
	Node   *Document      `json:"node"`
}

type ExportDocumentPDFInput struct {
	DocumentID gid.GID `json:"documentId"`
}

type ExportDocumentPDFPayload struct {
	Data string `json:"data"`
}

type ExportReportPDFInput struct {
	ReportID gid.GID `json:"reportId"`
}

type ExportReportPDFPayload struct {
	Data string `json:"data"`
}

type ExportTrustCenterFileInput struct {
	TrustCenterFileID gid.GID `json:"trustCenterFileId"`
}

type ExportTrustCenterFilePayload struct {
	Data string `json:"data"`
}

type Framework struct {
	ID           gid.GID `json:"id"`
	Name         string  `json:"name"`
	LightLogoURL *string `json:"lightLogoURL,omitempty"`
	DarkLogoURL  *string `json:"darkLogoURL,omitempty"`
}

func (Framework) IsNode()             {}
func (this Framework) GetID() gid.GID { return this.ID }

type Identity struct {
	ID            gid.GID   `json:"id"`
	Email         mail.Addr `json:"email"`
	FullName      string    `json:"fullName"`
	EmailVerified bool      `json:"emailVerified"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

func (Identity) IsNode()             {}
func (this Identity) GetID() gid.GID { return this.ID }

type Mutation struct {
}

type Organization struct {
	ID                 gid.GID `json:"id"`
	Name               string  `json:"name"`
	LogoURL            *string `json:"logoUrl,omitempty"`
	Description        *string `json:"description,omitempty"`
	WebsiteURL         *string `json:"websiteUrl,omitempty"`
	Email              *string `json:"email,omitempty"`
	HeadquarterAddress *string `json:"headquarterAddress,omitempty"`
}

func (Organization) IsNode()             {}
func (this Organization) GetID() gid.GID { return this.ID }

type PageInfo struct {
	HasNextPage     bool            `json:"hasNextPage"`
	HasPreviousPage bool            `json:"hasPreviousPage"`
	StartCursor     *page.CursorKey `json:"startCursor,omitempty"`
	EndCursor       *page.CursorKey `json:"endCursor,omitempty"`
}

type Query struct {
}

type Report struct {
	ID                     gid.GID `json:"id"`
	Filename               string  `json:"filename"`
	IsUserAuthorized       bool    `json:"isUserAuthorized"`
	HasUserRequestedAccess bool    `json:"hasUserRequestedAccess"`
}

func (Report) IsNode()             {}
func (this Report) GetID() gid.GID { return this.ID }

type RequestAccessesPayload struct {
	TrustCenterAccess *TrustCenterAccess `json:"trustCenterAccess"`
}

type RequestDocumentAccessInput struct {
	DocumentID gid.GID `json:"documentId"`
}

type RequestReportAccessInput struct {
	ReportID gid.GID `json:"reportId"`
}

type RequestTrustCenterFileAccessInput struct {
	TrustCenterFileID gid.GID `json:"trustCenterFileId"`
}

type SendMagicLinkInput struct {
	Email mail.Addr `json:"email"`
}

type SendMagicLinkPayload struct {
	Success bool `json:"success"`
}

type TrustCenter struct {
	ID                                gid.GID                         `json:"id"`
	Active                            bool                            `json:"active"`
	Slug                              string                          `json:"slug"`
	LogoFileURL                       *string                         `json:"logoFileUrl,omitempty"`
	DarkLogoFileURL                   *string                         `json:"darkLogoFileUrl,omitempty"`
	NdaFileName                       *string                         `json:"ndaFileName,omitempty"`
	NdaFileURL                        *string                         `json:"ndaFileUrl,omitempty"`
	Organization                      *Organization                   `json:"organization"`
	IsViewerMember                    bool                            `json:"isViewerMember"`
	HasAcceptedNonDisclosureAgreement bool                            `json:"hasAcceptedNonDisclosureAgreement"`
	Documents                         *DocumentConnection             `json:"documents"`
	Audits                            *AuditConnection                `json:"audits"`
	Vendors                           *VendorConnection               `json:"vendors"`
	References                        *TrustCenterReferenceConnection `json:"references"`
	TrustCenterFiles                  *TrustCenterFileConnection      `json:"trustCenterFiles"`
}

func (TrustCenter) IsNode()             {}
func (this TrustCenter) GetID() gid.GID { return this.ID }

type TrustCenterAccess struct {
	ID        gid.GID   `json:"id"`
	Email     mail.Addr `json:"email"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

func (TrustCenterAccess) IsNode()             {}
func (this TrustCenterAccess) GetID() gid.GID { return this.ID }

type TrustCenterFile struct {
	ID                     gid.GID `json:"id"`
	Name                   string  `json:"name"`
	Category               string  `json:"category"`
	IsUserAuthorized       bool    `json:"isUserAuthorized"`
	HasUserRequestedAccess bool    `json:"hasUserRequestedAccess"`
}

func (TrustCenterFile) IsNode()             {}
func (this TrustCenterFile) GetID() gid.GID { return this.ID }

type TrustCenterFileConnection struct {
	Edges    []*TrustCenterFileEdge `json:"edges"`
	PageInfo *PageInfo              `json:"pageInfo"`
}

type TrustCenterFileEdge struct {
	Cursor page.CursorKey   `json:"cursor"`
	Node   *TrustCenterFile `json:"node"`
}

type TrustCenterReference struct {
	ID          gid.GID `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	WebsiteURL  string  `json:"websiteUrl"`
	LogoURL     string  `json:"logoUrl"`
}

func (TrustCenterReference) IsNode()             {}
func (this TrustCenterReference) GetID() gid.GID { return this.ID }

type TrustCenterReferenceConnection struct {
	Edges    []*TrustCenterReferenceEdge `json:"edges"`
	PageInfo *PageInfo                   `json:"pageInfo"`
}

type TrustCenterReferenceEdge struct {
	Cursor page.CursorKey        `json:"cursor"`
	Node   *TrustCenterReference `json:"node"`
}

type Vendor struct {
	ID               gid.GID                 `json:"id"`
	Name             string                  `json:"name"`
	Description      *string                 `json:"description,omitempty"`
	Category         coredata.VendorCategory `json:"category"`
	WebsiteURL       *string                 `json:"websiteUrl,omitempty"`
	PrivacyPolicyURL *string                 `json:"privacyPolicyUrl,omitempty"`
	Countries        []coredata.CountryCode  `json:"countries"`
}

func (Vendor) IsNode()             {}
func (this Vendor) GetID() gid.GID { return this.ID }

type VendorEdge struct {
	Cursor page.CursorKey `json:"cursor"`
	Node   *Vendor        `json:"node"`
}

type VerifyMagicLinkInput struct {
	Token string `json:"token"`
}

type VerifyMagicLinkPayload struct {
	Success bool `json:"success"`
}
