import { ProboClient } from "../client/index.js";
import { listEvidence, getLatestEvidence, type EvidenceRecord } from "./store.js";

export interface SyncResult {
  documentId: string;
  title: string;
  source: string;
  type: string;
}

/**
 * Format evidence record as markdown for Probo document
 */
function formatEvidenceAsMarkdown(record: EvidenceRecord): string {
  const lines: string[] = [];

  lines.push(`# Compliance Evidence: ${record.type}`);
  lines.push("");
  lines.push(`**Source:** ${record.source}`);
  lines.push(`**Collected:** ${new Date(record.timestamp).toLocaleString()}`);
  lines.push(`**Status:** ${record.summary.status.toUpperCase()}`);
  if (record.summary.score !== undefined) {
    lines.push(`**Score:** ${record.summary.score}/100`);
  }
  lines.push("");

  // Metadata
  if (record.metadata) {
    lines.push("## Metadata");
    lines.push("");
    for (const [key, value] of Object.entries(record.metadata)) {
      if (value) {
        lines.push(`- **${key}:** ${value}`);
      }
    }
    lines.push("");
  }

  // Issues
  if (record.summary.issues.length > 0) {
    lines.push("## Issues Found");
    lines.push("");
    for (const issue of record.summary.issues) {
      lines.push(`- ${issue}`);
    }
    lines.push("");
  } else {
    lines.push("## Issues Found");
    lines.push("");
    lines.push("No issues found.");
    lines.push("");
  }

  // Raw data summary
  lines.push("## Evidence Data");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(record.data, null, 2));
  lines.push("```");
  lines.push("");

  // Footer
  lines.push("---");
  lines.push(`*Evidence ID: ${record.id}*`);
  lines.push(`*Generated by Probo Agent*`);

  return lines.join("\n");
}

/**
 * Format organization summary as markdown
 */
function formatSummaryAsMarkdown(
  source: string,
  records: EvidenceRecord[]
): string {
  const lines: string[] = [];
  const now = new Date().toLocaleString();

  lines.push(`# ${source.charAt(0).toUpperCase() + source.slice(1)} Compliance Summary`);
  lines.push("");
  lines.push(`**Generated:** ${now}`);
  lines.push(`**Records:** ${records.length}`);
  lines.push("");

  // Calculate overall stats
  const passing = records.filter(r => r.summary.status === "pass").length;
  const partial = records.filter(r => r.summary.status === "partial").length;
  const failing = records.filter(r => r.summary.status === "fail").length;
  const avgScore = records.reduce((sum, r) => sum + (r.summary.score || 0), 0) / records.length;

  lines.push("## Overview");
  lines.push("");
  lines.push(`| Status | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Passing | ${passing} |`);
  lines.push(`| Partial | ${partial} |`);
  lines.push(`| Failing | ${failing} |`);
  lines.push(`| **Average Score** | **${Math.round(avgScore)}/100** |`);
  lines.push("");

  // Individual records
  lines.push("## Details");
  lines.push("");

  for (const record of records) {
    const statusLabel = record.summary.status === "pass" ? "[PASS]" :
                       record.summary.status === "partial" ? "[PARTIAL]" : "[FAIL]";
    const name = record.metadata?.repository || record.metadata?.domain || record.type;

    lines.push(`### ${statusLabel} ${name}`);
    lines.push("");
    lines.push(`- **Score:** ${record.summary.score || "N/A"}/100`);
    lines.push(`- **Checked:** ${new Date(record.timestamp).toLocaleString()}`);

    if (record.summary.issues.length > 0) {
      lines.push(`- **Issues:**`);
      for (const issue of record.summary.issues) {
        lines.push(`  - ${issue}`);
      }
    } else {
      lines.push(`- **Issues:** None`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by Probo Agent*`);

  return lines.join("\n");
}

/**
 * Sync evidence to Probo as documents
 */
export async function syncEvidenceToProbo(
  client: ProboClient,
  organizationId: string,
  options?: {
    source?: "github" | "google" | "aws";
    type?: string;
    summaryOnly?: boolean;
  }
): Promise<SyncResult[]> {
  const results: SyncResult[] = [];

  // Get the current user as the approver
  const viewerId = await client.getFirstProfileId(organizationId);

  const sources = options?.source
    ? [options.source]
    : (["github", "google", "aws"] as const);

  for (const source of sources) {
    // Get latest evidence for this source
    const records = listEvidence({
      source,
      limit: options?.summaryOnly ? 1 : 50,
    });

    if (records.length === 0) continue;

    if (options?.summaryOnly) {
      // Just sync the summary
      const summaryRecords = listEvidence({ source, limit: 20 });
      if (summaryRecords.length === 0) continue;

      const content = formatSummaryAsMarkdown(source, summaryRecords);
      const title = `${source.charAt(0).toUpperCase() + source.slice(1)} Compliance Summary - ${new Date().toISOString().split("T")[0]}`;

      try {
        const result = await client.createDocument({
          organizationId,
          title,
          documentType: "OTHER",
          content,
          approverIds: [viewerId],
        });

        results.push({
          documentId: (result as { createDocument: { documentEdge: { node: { id: string } } } }).createDocument.documentEdge.node.id,
          title,
          source,
          type: "summary",
        });
      } catch (error) {
        console.error(`Failed to sync ${source} summary:`, error);
      }
    } else {
      // Sync individual records
      for (const record of records.slice(0, 10)) {
        // Limit to 10 most recent
        const content = formatEvidenceAsMarkdown(record);
        const title = `Evidence: ${record.source} - ${record.type} - ${new Date(record.timestamp).toISOString().split("T")[0]}`;

        try {
          const result = await client.createDocument({
            organizationId,
            title,
            documentType: "OTHER",
            content,
            approverIds: [viewerId],
          });

          results.push({
            documentId: (result as { createDocument: { documentEdge: { node: { id: string } } } }).createDocument.documentEdge.node.id,
            title,
            source: record.source,
            type: record.type,
          });
        } catch (error) {
          console.error(`Failed to sync ${record.type}:`, error);
        }
      }
    }
  }

  return results;
}

/**
 * Sync latest evidence summary to Probo
 */
export async function syncLatestSummaryToProbo(
  client: ProboClient,
  organizationId: string,
  source: "github" | "google" | "aws"
): Promise<SyncResult | null> {
  const records = listEvidence({ source, limit: 20 });
  if (records.length === 0) return null;

  const content = formatSummaryAsMarkdown(source, records);
  const title = `${source.charAt(0).toUpperCase() + source.slice(1)} Compliance Summary - ${new Date().toISOString().split("T")[0]}`;

  try {
    // Get the current user as the approver
    const viewerId = await client.getFirstProfileId(organizationId);

    const result = await client.createDocument({
      organizationId,
      title,
      documentType: "OTHER",
      content,
      approverIds: [viewerId],
    });

    return {
      documentId: (result as { createDocument: { documentEdge: { node: { id: string } } } }).createDocument.documentEdge.node.id,
      title,
      source,
      type: "summary",
    };
  } catch (error) {
    console.error(`Failed to sync ${source} summary:`, error);
    return null;
  }
}
