// Code generated by mcpgen. DO NOT EDIT.

package server

import (
	"context"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"go.probo.inc/probo/pkg/server/api/mcp/v1/types"
)

// ResolverInterface defines the interface that must be implemented by the parent resolver
type ResolverInterface interface {
	ListOrganizationsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListOrganizationsInput) (*mcp.CallToolResult, types.ListOrganizationsOutput, error)
	ListVendorsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListVendorsInput) (*mcp.CallToolResult, types.ListVendorsOutput, error)
	ListProfilesTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListProfilesInput) (*mcp.CallToolResult, types.ListProfilesOutput, error)
	AddVendorTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddVendorInput) (*mcp.CallToolResult, types.AddVendorOutput, error)
	UpdateVendorTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateVendorInput) (*mcp.CallToolResult, types.UpdateVendorOutput, error)
	GetProfileTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetProfileInput) (*mcp.CallToolResult, types.GetProfileOutput, error)
	UpdateProfileTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateProfileInput) (*mcp.CallToolResult, types.UpdateProfileOutput, error)
	ListRisksTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListRisksInput) (*mcp.CallToolResult, types.ListRisksOutput, error)
	GetRiskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetRiskInput) (*mcp.CallToolResult, types.GetRiskOutput, error)
	AddRiskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddRiskInput) (*mcp.CallToolResult, types.AddRiskOutput, error)
	UpdateRiskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateRiskInput) (*mcp.CallToolResult, types.UpdateRiskOutput, error)
	DeleteRiskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.DeleteRiskInput) (*mcp.CallToolResult, types.DeleteRiskOutput, error)
	ListMeasuresTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListMeasuresInput) (*mcp.CallToolResult, types.ListMeasuresOutput, error)
	GetMeasureTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetMeasureInput) (*mcp.CallToolResult, types.GetMeasureOutput, error)
	AddMeasureTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddMeasureInput) (*mcp.CallToolResult, types.AddMeasureOutput, error)
	UpdateMeasureTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateMeasureInput) (*mcp.CallToolResult, types.UpdateMeasureOutput, error)
	ListFrameworksTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListFrameworksInput) (*mcp.CallToolResult, types.ListFrameworksOutput, error)
	GetFrameworkTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetFrameworkInput) (*mcp.CallToolResult, types.GetFrameworkOutput, error)
	AddFrameworkTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddFrameworkInput) (*mcp.CallToolResult, types.AddFrameworkOutput, error)
	UpdateFrameworkTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateFrameworkInput) (*mcp.CallToolResult, types.UpdateFrameworkOutput, error)
	ListAssetsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListAssetsInput) (*mcp.CallToolResult, types.ListAssetsOutput, error)
	GetAssetTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetAssetInput) (*mcp.CallToolResult, types.GetAssetOutput, error)
	AddAssetTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddAssetInput) (*mcp.CallToolResult, types.AddAssetOutput, error)
	UpdateAssetTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateAssetInput) (*mcp.CallToolResult, types.UpdateAssetOutput, error)
	ListDataTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListDataInput) (*mcp.CallToolResult, types.ListDataOutput, error)
	GetDatumTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetDatumInput) (*mcp.CallToolResult, types.GetDatumOutput, error)
	AddDatumTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddDatumInput) (*mcp.CallToolResult, types.AddDatumOutput, error)
	UpdateDatumTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateDatumInput) (*mcp.CallToolResult, types.UpdateDatumOutput, error)
	ListNonconformitiesTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListNonconformitiesInput) (*mcp.CallToolResult, types.ListNonconformitiesOutput, error)
	GetNonconformityTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetNonconformityInput) (*mcp.CallToolResult, types.GetNonconformityOutput, error)
	AddNonconformityTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddNonconformityInput) (*mcp.CallToolResult, types.AddNonconformityOutput, error)
	UpdateNonconformityTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateNonconformityInput) (*mcp.CallToolResult, types.UpdateNonconformityOutput, error)
	ListObligationsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListObligationsInput) (*mcp.CallToolResult, types.ListObligationsOutput, error)
	GetObligationTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetObligationInput) (*mcp.CallToolResult, types.GetObligationOutput, error)
	AddObligationTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddObligationInput) (*mcp.CallToolResult, types.AddObligationOutput, error)
	UpdateObligationTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateObligationInput) (*mcp.CallToolResult, types.UpdateObligationOutput, error)
	ListContinualImprovementsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListContinualImprovementsInput) (*mcp.CallToolResult, types.ListContinualImprovementsOutput, error)
	GetContinualImprovementTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetContinualImprovementInput) (*mcp.CallToolResult, types.GetContinualImprovementOutput, error)
	AddContinualImprovementTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddContinualImprovementInput) (*mcp.CallToolResult, types.AddContinualImprovementOutput, error)
	UpdateContinualImprovementTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateContinualImprovementInput) (*mcp.CallToolResult, types.UpdateContinualImprovementOutput, error)
	ListAuditsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListAuditsInput) (*mcp.CallToolResult, types.ListAuditsOutput, error)
	GetAuditTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetAuditInput) (*mcp.CallToolResult, types.GetAuditOutput, error)
	AddAuditTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddAuditInput) (*mcp.CallToolResult, types.AddAuditOutput, error)
	UpdateAuditTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateAuditInput) (*mcp.CallToolResult, types.UpdateAuditOutput, error)
	ListControlsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListControlsInput) (*mcp.CallToolResult, types.ListControlsOutput, error)
	GetControlTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetControlInput) (*mcp.CallToolResult, types.GetControlOutput, error)
	AddControlTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddControlInput) (*mcp.CallToolResult, types.AddControlOutput, error)
	UpdateControlTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateControlInput) (*mcp.CallToolResult, types.UpdateControlOutput, error)
	LinkControlMeasureTool(ctx context.Context, req *mcp.CallToolRequest, input *types.LinkControlMeasureInput) (*mcp.CallToolResult, types.LinkControlMeasureOutput, error)
	UnlinkControlMeasureTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UnlinkControlMeasureInput) (*mcp.CallToolResult, types.UnlinkControlMeasureOutput, error)
	LinkControlDocumentTool(ctx context.Context, req *mcp.CallToolRequest, input *types.LinkControlDocumentInput) (*mcp.CallToolResult, types.LinkControlDocumentOutput, error)
	UnlinkControlDocumentTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UnlinkControlDocumentInput) (*mcp.CallToolResult, types.UnlinkControlDocumentOutput, error)
	LinkControlAuditTool(ctx context.Context, req *mcp.CallToolRequest, input *types.LinkControlAuditInput) (*mcp.CallToolResult, types.LinkControlAuditOutput, error)
	UnlinkControlAuditTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UnlinkControlAuditInput) (*mcp.CallToolResult, types.UnlinkControlAuditOutput, error)
	LinkControlSnapshotTool(ctx context.Context, req *mcp.CallToolRequest, input *types.LinkControlSnapshotInput) (*mcp.CallToolResult, types.LinkControlSnapshotOutput, error)
	UnlinkControlSnapshotTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UnlinkControlSnapshotInput) (*mcp.CallToolResult, types.UnlinkControlSnapshotOutput, error)
	ListTasksTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListTasksInput) (*mcp.CallToolResult, types.ListTasksOutput, error)
	GetTaskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetTaskInput) (*mcp.CallToolResult, types.GetTaskOutput, error)
	AddTaskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddTaskInput) (*mcp.CallToolResult, types.AddTaskOutput, error)
	UpdateTaskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateTaskInput) (*mcp.CallToolResult, types.UpdateTaskOutput, error)
	AssignTaskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AssignTaskInput) (*mcp.CallToolResult, types.AssignTaskOutput, error)
	UnassignTaskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UnassignTaskInput) (*mcp.CallToolResult, types.UnassignTaskOutput, error)
	DeleteTaskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.DeleteTaskInput) (*mcp.CallToolResult, types.DeleteTaskOutput, error)
	ListSnapshotsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListSnapshotsInput) (*mcp.CallToolResult, types.ListSnapshotsOutput, error)
	GetSnapshotTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetSnapshotInput) (*mcp.CallToolResult, types.GetSnapshotOutput, error)
	TakeSnapshotTool(ctx context.Context, req *mcp.CallToolRequest, input *types.TakeSnapshotInput) (*mcp.CallToolResult, types.TakeSnapshotOutput, error)
	ListDocumentsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListDocumentsInput) (*mcp.CallToolResult, types.ListDocumentsOutput, error)
	GetDocumentTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetDocumentInput) (*mcp.CallToolResult, types.GetDocumentOutput, error)
	AddDocumentTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddDocumentInput) (*mcp.CallToolResult, types.AddDocumentOutput, error)
	UpdateDocumentTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateDocumentInput) (*mcp.CallToolResult, types.UpdateDocumentOutput, error)
	ListDocumentVersionsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListDocumentVersionsInput) (*mcp.CallToolResult, types.ListDocumentVersionsOutput, error)
	GetDocumentVersionTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetDocumentVersionInput) (*mcp.CallToolResult, types.GetDocumentVersionOutput, error)
	CreateDraftDocumentVersionTool(ctx context.Context, req *mcp.CallToolRequest, input *types.CreateDraftDocumentVersionInput) (*mcp.CallToolResult, types.CreateDraftDocumentVersionOutput, error)
	UpdateDocumentVersionTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateDocumentVersionInput) (*mcp.CallToolResult, types.UpdateDocumentVersionOutput, error)
	DeleteDraftDocumentVersionTool(ctx context.Context, req *mcp.CallToolRequest, input *types.DeleteDraftDocumentVersionInput) (*mcp.CallToolResult, types.DeleteDraftDocumentVersionOutput, error)
	PublishDocumentVersionTool(ctx context.Context, req *mcp.CallToolRequest, input *types.PublishDocumentVersionInput) (*mcp.CallToolResult, types.PublishDocumentVersionOutput, error)
	DeleteDocumentTool(ctx context.Context, req *mcp.CallToolRequest, input *types.DeleteDocumentInput) (*mcp.CallToolResult, types.DeleteDocumentOutput, error)
	ListDocumentVersionSignaturesTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListDocumentVersionSignaturesInput) (*mcp.CallToolResult, types.ListDocumentVersionSignaturesOutput, error)
	GetDocumentVersionSignatureTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetDocumentVersionSignatureInput) (*mcp.CallToolResult, types.GetDocumentVersionSignatureOutput, error)
	RequestDocumentVersionSignatureTool(ctx context.Context, req *mcp.CallToolRequest, input *types.RequestDocumentVersionSignatureInput) (*mcp.CallToolResult, types.RequestDocumentVersionSignatureOutput, error)
	CancelSignatureRequestTool(ctx context.Context, req *mcp.CallToolRequest, input *types.CancelSignatureRequestInput) (*mcp.CallToolResult, types.CancelSignatureRequestOutput, error)
	ListMeetingsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListMeetingsInput) (*mcp.CallToolResult, types.ListMeetingsOutput, error)
	GetMeetingTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetMeetingInput) (*mcp.CallToolResult, types.GetMeetingOutput, error)
	AddMeetingTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddMeetingInput) (*mcp.CallToolResult, types.AddMeetingOutput, error)
	UpdateMeetingTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateMeetingInput) (*mcp.CallToolResult, types.UpdateMeetingOutput, error)
	DeleteMeetingTool(ctx context.Context, req *mcp.CallToolRequest, input *types.DeleteMeetingInput) (*mcp.CallToolResult, types.DeleteMeetingOutput, error)
	ListMeetingAttendeesTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListMeetingAttendeesInput) (*mcp.CallToolResult, types.ListMeetingAttendeesOutput, error)
}

// New creates a new MCP server instance with all handlers registered.
// Returns a fully configured *mcp.Server ready to be used with any transport.
func New(resolver ResolverInterface) *mcp.Server {
	server := mcp.NewServer(
		&mcp.Implementation{
			Name:    "Probo MCP Server",
			Version: "1.0.0",
		},
		nil,
	)

	registerToolHandlers(server, resolver)

	return server
}

func registerToolHandlers(server *mcp.Server, resolver ResolverInterface) {
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listOrganizations",
			Description:  "List all organizations the user has access to",
			InputSchema:  types.ListOrganizationsToolInputSchema,
			OutputSchema: types.ListOrganizationsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListOrganizationsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listVendors",
			Description:  "List all vendors for the organization",
			InputSchema:  types.ListVendorsToolInputSchema,
			OutputSchema: types.ListVendorsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListVendorsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listProfiles",
			Description:  "List all profiles for the organization",
			InputSchema:  types.ListProfilesToolInputSchema,
			OutputSchema: types.ListProfilesToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListProfilesTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addVendor",
			Description:  "Add a new vendor to the organization",
			InputSchema:  types.AddVendorToolInputSchema,
			OutputSchema: types.AddVendorToolOutputSchema,
		},
		resolver.AddVendorTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateVendor",
			Description:  "Update an existing vendor",
			InputSchema:  types.UpdateVendorToolInputSchema,
			OutputSchema: types.UpdateVendorToolOutputSchema,
		},
		resolver.UpdateVendorTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getProfile",
			Description:  "Get a profile by ID",
			InputSchema:  types.GetProfileToolInputSchema,
			OutputSchema: types.GetProfileToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetProfileTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateProfile",
			Description:  "Update an existing profile",
			InputSchema:  types.UpdateProfileToolInputSchema,
			OutputSchema: types.UpdateProfileToolOutputSchema,
		},
		resolver.UpdateProfileTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listRisks",
			Description:  "List all risks for the organization",
			InputSchema:  types.ListRisksToolInputSchema,
			OutputSchema: types.ListRisksToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListRisksTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getRisk",
			Description:  "Get a risk by ID",
			InputSchema:  types.GetRiskToolInputSchema,
			OutputSchema: types.GetRiskToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetRiskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addRisk",
			Description:  "Add a new risk to the organization",
			InputSchema:  types.AddRiskToolInputSchema,
			OutputSchema: types.AddRiskToolOutputSchema,
		},
		resolver.AddRiskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateRisk",
			Description:  "Update an existing risk",
			InputSchema:  types.UpdateRiskToolInputSchema,
			OutputSchema: types.UpdateRiskToolOutputSchema,
		},
		resolver.UpdateRiskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "deleteRisk",
			Description:  "Delete a risk",
			InputSchema:  types.DeleteRiskToolInputSchema,
			OutputSchema: types.DeleteRiskToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				DestructiveHint: boolPtr(true),
			},
		},
		resolver.DeleteRiskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listMeasures",
			Description:  "List all measures for the organization",
			InputSchema:  types.ListMeasuresToolInputSchema,
			OutputSchema: types.ListMeasuresToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListMeasuresTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getMeasure",
			Description:  "Get a measure by ID",
			InputSchema:  types.GetMeasureToolInputSchema,
			OutputSchema: types.GetMeasureToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetMeasureTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addMeasure",
			Description:  "Add a new measure to the organization",
			InputSchema:  types.AddMeasureToolInputSchema,
			OutputSchema: types.AddMeasureToolOutputSchema,
		},
		resolver.AddMeasureTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateMeasure",
			Description:  "Update an existing measure",
			InputSchema:  types.UpdateMeasureToolInputSchema,
			OutputSchema: types.UpdateMeasureToolOutputSchema,
		},
		resolver.UpdateMeasureTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listFrameworks",
			Description:  "List all frameworks for the organization",
			InputSchema:  types.ListFrameworksToolInputSchema,
			OutputSchema: types.ListFrameworksToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListFrameworksTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getFramework",
			Description:  "Get a framework by ID",
			InputSchema:  types.GetFrameworkToolInputSchema,
			OutputSchema: types.GetFrameworkToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetFrameworkTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addFramework",
			Description:  "Add a new framework to the organization",
			InputSchema:  types.AddFrameworkToolInputSchema,
			OutputSchema: types.AddFrameworkToolOutputSchema,
		},
		resolver.AddFrameworkTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateFramework",
			Description:  "Update an existing framework",
			InputSchema:  types.UpdateFrameworkToolInputSchema,
			OutputSchema: types.UpdateFrameworkToolOutputSchema,
		},
		resolver.UpdateFrameworkTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listAssets",
			Description:  "List all assets for the organization",
			InputSchema:  types.ListAssetsToolInputSchema,
			OutputSchema: types.ListAssetsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListAssetsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getAsset",
			Description:  "Get an asset by ID",
			InputSchema:  types.GetAssetToolInputSchema,
			OutputSchema: types.GetAssetToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetAssetTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addAsset",
			Description:  "Add a new asset to the organization",
			InputSchema:  types.AddAssetToolInputSchema,
			OutputSchema: types.AddAssetToolOutputSchema,
		},
		resolver.AddAssetTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateAsset",
			Description:  "Update an existing asset",
			InputSchema:  types.UpdateAssetToolInputSchema,
			OutputSchema: types.UpdateAssetToolOutputSchema,
		},
		resolver.UpdateAssetTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listData",
			Description:  "List all data for the organization",
			InputSchema:  types.ListDataToolInputSchema,
			OutputSchema: types.ListDataToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListDataTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getDatum",
			Description:  "Get a datum by ID",
			InputSchema:  types.GetDatumToolInputSchema,
			OutputSchema: types.GetDatumToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetDatumTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addDatum",
			Description:  "Add a new datum to the organization",
			InputSchema:  types.AddDatumToolInputSchema,
			OutputSchema: types.AddDatumToolOutputSchema,
		},
		resolver.AddDatumTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateDatum",
			Description:  "Update an existing datum",
			InputSchema:  types.UpdateDatumToolInputSchema,
			OutputSchema: types.UpdateDatumToolOutputSchema,
		},
		resolver.UpdateDatumTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listNonconformities",
			Description:  "List all nonconformities for the organization",
			InputSchema:  types.ListNonconformitiesToolInputSchema,
			OutputSchema: types.ListNonconformitiesToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListNonconformitiesTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getNonconformity",
			Description:  "Get a nonconformity by ID",
			InputSchema:  types.GetNonconformityToolInputSchema,
			OutputSchema: types.GetNonconformityToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetNonconformityTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addNonconformity",
			Description:  "Add a new nonconformity to the organization",
			InputSchema:  types.AddNonconformityToolInputSchema,
			OutputSchema: types.AddNonconformityToolOutputSchema,
		},
		resolver.AddNonconformityTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateNonconformity",
			Description:  "Update an existing nonconformity",
			InputSchema:  types.UpdateNonconformityToolInputSchema,
			OutputSchema: types.UpdateNonconformityToolOutputSchema,
		},
		resolver.UpdateNonconformityTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listObligations",
			Description:  "List all obligations for the organization",
			InputSchema:  types.ListObligationsToolInputSchema,
			OutputSchema: types.ListObligationsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListObligationsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getObligation",
			Description:  "Get an obligation by ID",
			InputSchema:  types.GetObligationToolInputSchema,
			OutputSchema: types.GetObligationToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetObligationTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addObligation",
			Description:  "Add a new obligation to the organization",
			InputSchema:  types.AddObligationToolInputSchema,
			OutputSchema: types.AddObligationToolOutputSchema,
		},
		resolver.AddObligationTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateObligation",
			Description:  "Update an existing obligation",
			InputSchema:  types.UpdateObligationToolInputSchema,
			OutputSchema: types.UpdateObligationToolOutputSchema,
		},
		resolver.UpdateObligationTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listContinualImprovements",
			Description:  "List all continual improvements for the organization",
			InputSchema:  types.ListContinualImprovementsToolInputSchema,
			OutputSchema: types.ListContinualImprovementsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListContinualImprovementsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getContinualImprovement",
			Description:  "Get a continual improvement by ID",
			InputSchema:  types.GetContinualImprovementToolInputSchema,
			OutputSchema: types.GetContinualImprovementToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetContinualImprovementTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addContinualImprovement",
			Description:  "Add a new continual improvement to the organization",
			InputSchema:  types.AddContinualImprovementToolInputSchema,
			OutputSchema: types.AddContinualImprovementToolOutputSchema,
		},
		resolver.AddContinualImprovementTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateContinualImprovement",
			Description:  "Update an existing continual improvement",
			InputSchema:  types.UpdateContinualImprovementToolInputSchema,
			OutputSchema: types.UpdateContinualImprovementToolOutputSchema,
		},
		resolver.UpdateContinualImprovementTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listAudits",
			Description:  "List all audits for the organization",
			InputSchema:  types.ListAuditsToolInputSchema,
			OutputSchema: types.ListAuditsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListAuditsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getAudit",
			Description:  "Get an audit by ID",
			InputSchema:  types.GetAuditToolInputSchema,
			OutputSchema: types.GetAuditToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetAuditTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addAudit",
			Description:  "Add a new audit to the organization",
			InputSchema:  types.AddAuditToolInputSchema,
			OutputSchema: types.AddAuditToolOutputSchema,
		},
		resolver.AddAuditTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateAudit",
			Description:  "Update an existing audit",
			InputSchema:  types.UpdateAuditToolInputSchema,
			OutputSchema: types.UpdateAuditToolOutputSchema,
		},
		resolver.UpdateAuditTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listControls",
			Description:  "List all controls for the organization or framework",
			InputSchema:  types.ListControlsToolInputSchema,
			OutputSchema: types.ListControlsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListControlsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getControl",
			Description:  "Get a control by ID",
			InputSchema:  types.GetControlToolInputSchema,
			OutputSchema: types.GetControlToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetControlTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addControl",
			Description:  "Add a new control to a framework",
			InputSchema:  types.AddControlToolInputSchema,
			OutputSchema: types.AddControlToolOutputSchema,
		},
		resolver.AddControlTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateControl",
			Description:  "Update an existing control",
			InputSchema:  types.UpdateControlToolInputSchema,
			OutputSchema: types.UpdateControlToolOutputSchema,
		},
		resolver.UpdateControlTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "linkControlMeasure",
			Description:  "Link a measure to a control",
			InputSchema:  types.LinkControlMeasureToolInputSchema,
			OutputSchema: types.LinkControlMeasureToolOutputSchema,
		},
		resolver.LinkControlMeasureTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "unlinkControlMeasure",
			Description:  "Unlink a measure from a control",
			InputSchema:  types.UnlinkControlMeasureToolInputSchema,
			OutputSchema: types.UnlinkControlMeasureToolOutputSchema,
		},
		resolver.UnlinkControlMeasureTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "linkControlDocument",
			Description:  "Link a document to a control",
			InputSchema:  types.LinkControlDocumentToolInputSchema,
			OutputSchema: types.LinkControlDocumentToolOutputSchema,
		},
		resolver.LinkControlDocumentTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "unlinkControlDocument",
			Description:  "Unlink a document from a control",
			InputSchema:  types.UnlinkControlDocumentToolInputSchema,
			OutputSchema: types.UnlinkControlDocumentToolOutputSchema,
		},
		resolver.UnlinkControlDocumentTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "linkControlAudit",
			Description:  "Link an audit to a control",
			InputSchema:  types.LinkControlAuditToolInputSchema,
			OutputSchema: types.LinkControlAuditToolOutputSchema,
		},
		resolver.LinkControlAuditTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "unlinkControlAudit",
			Description:  "Unlink an audit from a control",
			InputSchema:  types.UnlinkControlAuditToolInputSchema,
			OutputSchema: types.UnlinkControlAuditToolOutputSchema,
		},
		resolver.UnlinkControlAuditTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "linkControlSnapshot",
			Description:  "Link a snapshot to a control",
			InputSchema:  types.LinkControlSnapshotToolInputSchema,
			OutputSchema: types.LinkControlSnapshotToolOutputSchema,
		},
		resolver.LinkControlSnapshotTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "unlinkControlSnapshot",
			Description:  "Unlink a snapshot from a control",
			InputSchema:  types.UnlinkControlSnapshotToolInputSchema,
			OutputSchema: types.UnlinkControlSnapshotToolOutputSchema,
		},
		resolver.UnlinkControlSnapshotTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listTasks",
			Description:  "List all tasks for the organization or measure",
			InputSchema:  types.ListTasksToolInputSchema,
			OutputSchema: types.ListTasksToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListTasksTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getTask",
			Description:  "Get a task by ID",
			InputSchema:  types.GetTaskToolInputSchema,
			OutputSchema: types.GetTaskToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetTaskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addTask",
			Description:  "Add a new task to the organization",
			InputSchema:  types.AddTaskToolInputSchema,
			OutputSchema: types.AddTaskToolOutputSchema,
		},
		resolver.AddTaskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateTask",
			Description:  "Update an existing task",
			InputSchema:  types.UpdateTaskToolInputSchema,
			OutputSchema: types.UpdateTaskToolOutputSchema,
		},
		resolver.UpdateTaskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "assignTask",
			Description:  "Assign a task to a person",
			InputSchema:  types.AssignTaskToolInputSchema,
			OutputSchema: types.AssignTaskToolOutputSchema,
		},
		resolver.AssignTaskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "unassignTask",
			Description:  "Unassign a task from a person",
			InputSchema:  types.UnassignTaskToolInputSchema,
			OutputSchema: types.UnassignTaskToolOutputSchema,
		},
		resolver.UnassignTaskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "deleteTask",
			Description:  "Delete a task",
			InputSchema:  types.DeleteTaskToolInputSchema,
			OutputSchema: types.DeleteTaskToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				DestructiveHint: boolPtr(true),
			},
		},
		resolver.DeleteTaskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listSnapshots",
			Description:  "List all snapshots for the organization",
			InputSchema:  types.ListSnapshotsToolInputSchema,
			OutputSchema: types.ListSnapshotsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListSnapshotsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getSnapshot",
			Description:  "Get a snapshot by ID",
			InputSchema:  types.GetSnapshotToolInputSchema,
			OutputSchema: types.GetSnapshotToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetSnapshotTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "takeSnapshot",
			Description:  "Take a snapshot of a collection of objects (risks, vendors, assets, data, nonconformities, obligations, continual improvements, or processing activities)",
			InputSchema:  types.TakeSnapshotToolInputSchema,
			OutputSchema: types.TakeSnapshotToolOutputSchema,
		},
		resolver.TakeSnapshotTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listDocuments",
			Description:  "List all documents for the organization",
			InputSchema:  types.ListDocumentsToolInputSchema,
			OutputSchema: types.ListDocumentsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListDocumentsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getDocument",
			Description:  "Get a document by ID",
			InputSchema:  types.GetDocumentToolInputSchema,
			OutputSchema: types.GetDocumentToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetDocumentTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addDocument",
			Description:  "Add a new document to the organization",
			InputSchema:  types.AddDocumentToolInputSchema,
			OutputSchema: types.AddDocumentToolOutputSchema,
		},
		resolver.AddDocumentTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateDocument",
			Description:  "Update an existing document",
			InputSchema:  types.UpdateDocumentToolInputSchema,
			OutputSchema: types.UpdateDocumentToolOutputSchema,
		},
		resolver.UpdateDocumentTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listDocumentVersions",
			Description:  "List all versions for a document",
			InputSchema:  types.ListDocumentVersionsToolInputSchema,
			OutputSchema: types.ListDocumentVersionsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListDocumentVersionsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getDocumentVersion",
			Description:  "Get a document version by ID",
			InputSchema:  types.GetDocumentVersionToolInputSchema,
			OutputSchema: types.GetDocumentVersionToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetDocumentVersionTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "createDraftDocumentVersion",
			Description:  "Create a new draft version from the latest published version",
			InputSchema:  types.CreateDraftDocumentVersionToolInputSchema,
			OutputSchema: types.CreateDraftDocumentVersionToolOutputSchema,
		},
		resolver.CreateDraftDocumentVersionTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateDocumentVersion",
			Description:  "Update an existing draft document version content",
			InputSchema:  types.UpdateDocumentVersionToolInputSchema,
			OutputSchema: types.UpdateDocumentVersionToolOutputSchema,
		},
		resolver.UpdateDocumentVersionTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "deleteDraftDocumentVersion",
			Description:  "Delete a draft document version",
			InputSchema:  types.DeleteDraftDocumentVersionToolInputSchema,
			OutputSchema: types.DeleteDraftDocumentVersionToolOutputSchema,
		},
		resolver.DeleteDraftDocumentVersionTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "publishDocumentVersion",
			Description:  "Publish a draft document version",
			InputSchema:  types.PublishDocumentVersionToolInputSchema,
			OutputSchema: types.PublishDocumentVersionToolOutputSchema,
		},
		resolver.PublishDocumentVersionTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "deleteDocument",
			Description:  "Delete a document",
			InputSchema:  types.DeleteDocumentToolInputSchema,
			OutputSchema: types.DeleteDocumentToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				DestructiveHint: boolPtr(true),
			},
		},
		resolver.DeleteDocumentTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listDocumentVersionSignatures",
			Description:  "List all signatures for a document version",
			InputSchema:  types.ListDocumentVersionSignaturesToolInputSchema,
			OutputSchema: types.ListDocumentVersionSignaturesToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListDocumentVersionSignaturesTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getDocumentVersionSignature",
			Description:  "Get a document version signature by ID",
			InputSchema:  types.GetDocumentVersionSignatureToolInputSchema,
			OutputSchema: types.GetDocumentVersionSignatureToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetDocumentVersionSignatureTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "requestDocumentVersionSignature",
			Description:  "Request a signature for a document version",
			InputSchema:  types.RequestDocumentVersionSignatureToolInputSchema,
			OutputSchema: types.RequestDocumentVersionSignatureToolOutputSchema,
		},
		resolver.RequestDocumentVersionSignatureTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "cancelSignatureRequest",
			Description:  "Cancel a document version signature request",
			InputSchema:  types.CancelSignatureRequestToolInputSchema,
			OutputSchema: types.CancelSignatureRequestToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				DestructiveHint: boolPtr(true),
			},
		},
		resolver.CancelSignatureRequestTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listMeetings",
			Description:  "List all meetings for the organization",
			InputSchema:  types.ListMeetingsToolInputSchema,
			OutputSchema: types.ListMeetingsToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListMeetingsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getMeeting",
			Description:  "Get a meeting by ID",
			InputSchema:  types.GetMeetingToolInputSchema,
			OutputSchema: types.GetMeetingToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.GetMeetingTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addMeeting",
			Description:  "Add a new meeting to the organization",
			InputSchema:  types.AddMeetingToolInputSchema,
			OutputSchema: types.AddMeetingToolOutputSchema,
		},
		resolver.AddMeetingTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateMeeting",
			Description:  "Update an existing meeting",
			InputSchema:  types.UpdateMeetingToolInputSchema,
			OutputSchema: types.UpdateMeetingToolOutputSchema,
		},
		resolver.UpdateMeetingTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "deleteMeeting",
			Description:  "Delete a meeting",
			InputSchema:  types.DeleteMeetingToolInputSchema,
			OutputSchema: types.DeleteMeetingToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				DestructiveHint: boolPtr(true),
			},
		},
		resolver.DeleteMeetingTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listMeetingAttendees",
			Description:  "List all attendees for a meeting",
			InputSchema:  types.ListMeetingAttendeesToolInputSchema,
			OutputSchema: types.ListMeetingAttendeesToolOutputSchema,
			Annotations: &mcp.ToolAnnotations{
				ReadOnlyHint:   true,
				IdempotentHint: true,
			},
		},
		resolver.ListMeetingAttendeesTool,
	)
}

func boolPtr(b bool) *bool {
	return &b
}
