name: "trufflehog"

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: "trufflesecurity/trufflehog@041f07e9df901a1038a528e5525b0226d04dd5ea" # main
        with:
          extra_args: "--results=verified,unknown"
